[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://dinamikgoz.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 