name = "dinamik-goz"
compatibility_date = "2024-04-19"

[build]
command = "npm install && npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22.14.0"
NPM_VERSION = "11.2.0"

[site]
bucket = ".next" 